#!/bin/bash

# led test
echo Quiz Start!!!
echo y > /dev/myled0
sleep 1
echo z > /dev/myled0
sleep 1
echo Q1:1 + 3 = ?
sleep 0.2
echo 1 > /dev/myled0
sleep 0.1
echo ⭕
sleep 0.3
echo 2 > /dev/myled0
sleep 1
echo Q2:If x^2 + 5x = 14, x = ?
sleep 0.2
echo a > /dev/myled0
sleep 0.1
echo ⭕
sleep 0.3
echo b > /dev/myled0
sleep 1
echo Q3:2^23543 / 0 = ?
sleep 5
echo 5
sleep 1
echo 4
sleep 1
echo 3
sleep 1
echo 2
sleep 1 
echo 1
sleep 0.1
echo A > /dev/myled0
sleep 1
echo ❌
echo B > /dev/myled0
sleep 0.7
echo 1 > /dev/myled0
sleep 0.05
echo 2 > /dev/myled0
echo a > /dev/myled0
sleep 0.05
echo b > /dev/myled0
echo A > /dev/myled0
sleep 0.05
echo B > /dev/myled0
sleep 1.5
echo Answer:
sleep 1.5
echo        None
sleep 0.5
echo y > /dev/myled0
sleep 1
echo z > /dev/myled0
sleep 1
