#!/bin/bash

:<<'#COMMENT_OUT'
    Copyright (C) 2021 Yusuke Yamasaki

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#COMMENT_OUT

# author : Yusuke Yamasaki
# lisence : GPL
# description : Code for LED-control
# version : 0.0.1

echo Start

echo Quiz Start!!!
echo y > /dev/myled0
sleep 1
echo z > /dev/myled0
sleep 1
echo Q1:1 + 4 = ?
sleep 0.2
echo 1 > /dev/myled0
echo A > /dev/myled0
sleep 0.1
echo ⭕
sleep 0.3
echo 2 > /dev/myled0
echo B > /dev/myled0
sleep 1
echo Q2:If x^2 + 5x = 14 then, x = ?
sleep 0.2
echo a > /dev/myled0
sleep 0.1
echo ⭕
sleep 0.3
echo b > /dev/myled0
sleep 1
echo Q3:2^23543 / 0 = ?
sleep 5
echo 5
sleep 1
echo 4
sleep 1
echo 3
sleep 1
echo 2
sleep 1 
echo 1
sleep 0.1
echo A > /dev/myled0
sleep 1
echo ❌
echo B > /dev/myled0
sleep 0.7
echo 1 > /dev/myled0
sleep 0.05
echo 2 > /dev/myled0
echo a > /dev/myled0
sleep 0.05
echo b > /dev/myled0
echo A > /dev/myled0
sleep 0.05
echo B > /dev/myled0
sleep 1.5
echo Answer:
sleep 1.5
echo        None
sleep 0.5
echo 1 > /dev/myled0
echo A > /dev/myled0
sleep 0.5
echo 2 > /dev/myled0
echo B > /dev/myled0
echo a > /dev/myled0
sleep 0.5
echo 1 > /dev/myled0
echo A > /dev/myled0
echo b > /dev/myled0
sleep 0.5
echo 2 > /dev/myled0
echo B > /dev/myled0
echo a > /dev/myled0
sleep 0.5
echo 1 > /dev/myled0
echo A > /dev/myled0
echo b > /dev/myled0
sleep 0.5
echo 2 > /dev/myled0
echo B > /dev/myled0
echo a > /dev/myled0
sleep 0.5
echo 1 > /dev/myled0
echo A > /dev/myled0
echo b > /dev/myled0
sleep 0.5
echo 2 > /dev/myled0
echo B > /dev/myled0
echo a > /dev/myled0
sleep 0.5
echo y > /dev/myled0
sleep 1.0
echo z > /dev/myled0
sleep 1.0

echo Finish
